### ISSUE TITLE
AdapterNotSpecified - Rake tasks not working

### ISSUE THREAD

**Issue by phippg** [sinatra-activerecord/sinatra-activerecord#36]
Hello,
just recently I installed this gem and wanted to put it to good use, followed the instructions, Sinatra app ran. But when I wanted to mess with the actual database via rake tasks I always get an error of "ActiveRecord::AdapterNotSpecified 'development' database is not configured".

I am using a config/database.yml file which has the following contents:

```
development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3
```

I don't know whether the error is on my side, or if there is just something incompatible.

Thanks in advance!
